### ISSUE TITLE
Error while exporting an Ad Hoc build

### ISSUE THREAD

**Issue by RonakShah** [atomaxinc/SkaleKit#1]
When I export a build, I'm getting an error like:

Failed to verify bitcode in SkaleKit.framework/SkaleKit:
error: Bundle only contains bitcode-marker .../SkaleKit.framework/Skale.Kit (armv7)

Happens on Xcode 9.2 and 9.4.1

**Comment by atomaxinc** [comment]
Plz try the version 0.4.1
