### ISSUE TITLE
Tare and other functions

### ISSUE THREAD

**Issue by ajstokar** [atomaxinc/SkaleKit#2]
Hi @RyanYC .  This is a fantastic idea!  I'm working on a project that would require a scale integration like this.  Is this SDK still being actively supported?  If so, do you have plans to release further functionality like a Tare command?

Thanks!
Adam

**Comment by RyanYC** [comment]
Hi @ajstokar.  Yes, we do have Tare functionality in the current version. We also have a battery life reading function and there is a callback function available for clicking the scale's button events. You can check the header files to see what functionalities are released.  Thanks.

**Comment by ajstokar** [comment]
Found it, thanks.
