### ISSUE TITLE
Question: Ble Characteristic For Tare?

### ISSUE THREAD

**Issue by mpkasp** [atomaxinc/SkaleKit#3]
Hi - I know this is not an iOS SkaleKit specific question, but I'm interested in using a pre-existing BLE Library in an Ionic app to control a Skale so it will be cross-platform. Any chance you can share the BLE characteristic & command to tare a Skale over BLE?

Thanks!

**Comment by atomaxinc** [comment]
Please send a mail to service@atomaxinc.com to ask for Skale BLE specifications.
